{% set name = "multiuserfilelock" %}
{% set version = "0.0.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/multiuserfilelock-{{ version }}.tar.gz
  sha256: d9e9bf0363c408d2e4cb5cecdc910592517a41c37cf3506ea413843c70d2b1f9
  patches:
    - patch_windows_test.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - filelock

test:
  imports:
    - multiuserfilelock
  commands:
    - pip check
    - pytest --pyargs multiuserfilelock
  requires:
    - pip
    - pytest

about:
  home: https://github.com/ramonaoptics/python-multiuserfilelock
  summary: A lock to share resources between users based on filelock.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
