{% set name = "multiuserfilelock" %}
{% set version = "0.0.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/multiuserfilelock-{{ version }}.tar.gz
  sha256: a0d276a1bd5595ac0e2801e86873e4b2fcaba1bfcbf22e632f21e45075ca4a79

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - filelock !=3.11.0

test:
  imports:
    - multiuserfilelock
  commands:
    - pip check
    - pytest --pyargs multiuserfilelock
  requires:
    - pip
    - pytest

about:
  home: https://github.com/ramonaoptics/python-multiuserfilelock
  summary: A lock to share resources between users based on filelock.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
