{% set version = "0.0.9" %}

package:
  name: multiuserfilelock
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/multiuserfilelock/multiuserfilelock-{{ version }}.tar.gz
  sha256: 24629e7210a74152bbec8fa75f46cd47632fe24b510d64eb876d70ea0e6b2de9

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - filelock !=3.11.0,!=3.13.0

test:
  imports:
    - multiuserfilelock
  commands:
    - pip check
    # hmaarrfk - 2024/12 i think the CIs changed and now the tests
    # stopped working
    # - pytest --pyargs multiuserfilelock
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/ramonaoptics/python-multiuserfilelock
  summary: A lock to share resources between users based on filelock.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
