{% set name = "multiuserfilelock" %}
{% set version = "0.0.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/multiuserfilelock-{{ version }}.tar.gz
  sha256: 24629e7210a74152bbec8fa75f46cd47632fe24b510d64eb876d70ea0e6b2de9

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - filelock !=3.11.0,!=3.13.0

test:
  imports:
    - multiuserfilelock
  commands:
    - pip check
    - pytest --pyargs multiuserfilelock
  requires:
    - pip
    - pytest

about:
  home: https://github.com/ramonaoptics/python-multiuserfilelock
  summary: A lock to share resources between users based on filelock.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
